### PR TITLE
Roboto Flex animation improvements

### PR DESCRIPTION
**Pull request by RoelN**
I needed a more appealing animation demo. Animation effects are clearer because of the bigger text, and live updatin' CSS better explains what's going on.

rfa

### CODE REVIEW

**Comment by RoelN** [comment]
@chrissam42 Would you mind reviewing this PR? (cc @davelab6)

**Comment by RoelN** [comment]
(Failing build came _free_ with the master branch! Not guilty.)

**Comment by chrissam42** [comment]
Tested in FF, Chrome, Safari, looks great.

**Comment by RoelN** [comment]
Ta very much!

**Pull request merged**
